name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libfreetype6-dev libjpeg-dev

      - name: Install buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.34
          pip install --upgrade buildozer

      # YEH SABSE ZAROORI STEP HAI - Pehle Clean, Phir Build
      - name: Clean and Build with Buildozer
        run: |
          buildozer android clean
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: dsr-app-apk
          path: bin/*.apk
