name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Hum pehle wala environment setup step use karenge jo dependencies install karta hai
      - name: Set up build environment for dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git \
              zip \
              unzip \
              build-essential \
              python3-pip \
              ffmpeg \
              libsdl2-dev \
              libsdl2-image-dev \
              libsdl2-mixer-dev \
              libsdl2-ttf-dev \
              libportmidi-dev \
              libswscale-dev \
              libavformat-dev \
              libavcodec-dev \
              zlib1g-dev \
              libgstreamer1.0-dev \
              gstreamer1.0-plugins-base \
              gstreamer1.0-plugins-good
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Yahan standard Buildozer Action use ho raha hai
      - name: Build with Buildozer
        uses: arsenetar/kivy-buildozer-action@v1.3.1
        id: buildozer
        with:
          # Aapki buildozer.spec file kahan hai
          spec_path: buildozer.spec
          # Aap release ya debug build bana sakte hain
          build_mode: debug

      # Yahan APK ko upload karne ka step hai
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: dsr-app-apk
          # Ye path Buildozer Action se milta hai
          path: ${{ steps.buildozer.outputs.apk_path }}
