name: Build Kivy APK

on: [push]

jobs:
  build:
    # Hum stable ubuntu-22.04 istemal kar rahe hain
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Android build ke liye Java zaroori hai
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Zaroori system libraries install karna
      - name: Install system dependencies
        run: |
          sudo apt-get update
          # Yahan humne libjpeg-dev add kiya hai - YEH HI ASLI FIX HAI
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libfreetype6-dev libjpeg-dev

      # Buildozer aur doosri Python libraries install karna
      - name: Install buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.34
          pip install --upgrade buildozer

      # Ab hum Buildozer ko direct chala rahe hain
      - name: Build with Buildozer
        run: buildozer -v android debug

      # APK ko upload karna
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: dsr-app-apk
          # Buildozer 'bin' folder me APK banata hai
          path: bin/*.apk
