name: Build Kivy APK

on: [push]

jobs:
  build:
    # YEH SABSE ZAROORI BADLAV HAI: Hum 22.04 use kar rahe hain
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Hum build environment ko zaroori tools ke saath taiyyar karenge
      - name: Set up build environment for dependencies
        run: |
          sudo apt-get update
          # Yahan humne libffi-dev aur libfreetype6-dev add kiye hain
          sudo apt-get install -y \
              git \
              zip \
              unzip \
              build-essential \
              python3-pip \
              ffmpeg \
              libsdl2-dev \
              libsdl2-image-dev \
              libsdl2-mixer-dev \
              libsdl2-ttf-dev \
              libportmidi-dev \
              libswscale-dev \
              libavformat-dev \
              libavcodec-dev \
              zlib1g-dev \
              libgstreamer1.0-dev \
              gstreamer1.0-plugins-base \
              gstreamer1.0-plugins-good \
              libffi-dev \
              libfreetype6-dev
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Standard Buildozer Action, isme koi badlav nahi hai
      - name: Build with Buildozer
        uses: arsenetar/kivy-buildozer-action@v1.3.1
        id: buildozer
        with:
          spec_path: buildozer.spec
          build_mode: debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: dsr-app-apk
          path: ${{ steps.buildozer.outputs.apk_path }}
